services:
#  react:
#    build: react
#    environment:
#      - BACKEND_BASE_URL=http://spring:8177/api
#    ports:
#      - "80:80"
#    depends_on:
#      - spring


  spring:
    image: maven:3.9.16-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./hsms:/app
    command: mvn spring-boot:run
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - WGMGR_DB_CONN_STR=postgresql://db:5432/hsms
    ports:
      - "8177:8177"
    networks:
      - monitoring
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:main
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:main-ubuntu
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - monitoring

  db:
    image: postgres:18.3
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=hsms
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - monitoring


configs:
  prometheus_config:
    file: prometheus/prometheus.yml

networks:
  monitoring:

volumes:
  pgdata: