spring.application.name=hsms_spring

spring.datasource.url=jdbc:${WGMGR_DB_CONN_STR}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.deserialization.fail-on-missing-creator-properties=true

server.port=8177

# use @ApplicationModule for each module
spring.modulith.detection-strategy=explicitly-annotated


#SpringDoc /v3/api-docs endpoint is enabled by default
springdoc.api-docs.enabled=true
#SpringDoc /swagger-ui.html endpoint is enabled by default
springdoc.swagger-ui.enabled=true

# Actuator endpoints
management.endpoints.web.exposure.include=health,modulith