INSERT INTO role (name)
SELECT 'ROLE_SUPPLY_MANAGER'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ROLE_SUPPLY_MANAGER');

INSERT INTO role (name)
SELECT 'ROLE_HARVESTER_CREW'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ROLE_HARVESTER_CREW');

INSERT INTO role (name)
SELECT 'ROLE_INSURANCE_CONTOUR_OPERATOR'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ROLE_INSURANCE_CONTOUR_OPERATOR');

INSERT INTO role (name)
SELECT 'ROLE_SECURITY_HEADQUARTERS_OPERATOR'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ROLE_SECURITY_HEADQUARTERS_OPERATOR');

INSERT INTO role (name)
SELECT 'ROLE_ADMINISTRATOR'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ROLE_ADMINISTRATOR');

INSERT INTO role (name)
SELECT 'ROLE_OPERATIONS_MANAGEMENT'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ROLE_OPERATIONS_MANAGEMENT');
