INSERT INTO role (name)
VALUES ('ROLE_SUPPLY_MANAGER')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role (name)
VALUES ('ROLE_HARVESTER_CREW')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role (name)
VALUES ('ROLE_INSURANCE_CONTOUR_OPERATOR')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role (name)
VALUES ('ROLE_SECURITY_HEADQUARTERS_OPERATOR')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role (name)
VALUES ('ROLE_ADMINISTRATOR')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role (name)
VALUES ('ROLE_OPERATIONS MANUAL')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role (name)
VALUES ('ROLE_SUPERVISOR')
ON CONFLICT (name) DO NOTHING;